/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _plugin1_import_h__
#define _plugin1_import_h__

# import <MulleObjC/MulleObjC.h>   // MulleObjC

#endif
