#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

 

set( PRIVATE_HEADERS
import-private.h
include-private.h
)

set( PUBLIC_HEADERS
MulleObjCLoader+plugin2.h
import.h
include.h
plugin2.h
) 

