/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_load_two_universes_import_h__
#define _mulle_load_two_universes_import_h__

# import <plugin1/plugin1.h>   // src/plugin1

# import <plugin2/plugin2.h>   // src/plugin2

#endif
