/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_load_two_universes_import_private_h__
#define _mulle_load_two_universes_import_private_h__

/* no headers */

#endif
